# Generated by Django 4.0 on 2021-12-29 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodesOnLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код на уровне')),
            ],
            options={
                'verbose_name': 'Код на уровне',
                'verbose_name_plural': 'Коды на уровне',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень №')),
                ('title', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('question', models.TextField(blank=True, verbose_name='Загадка на уровне')),
                ('question_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото для загадки')),
                ('spoiler', models.TextField(blank=True, verbose_name='Спойлер')),
                ('spoiler_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото для спойлера')),
                ('hint1', models.CharField(max_length=255, verbose_name='Подсказка 1')),
                ('hint2', models.CharField(max_length=255, verbose_name='Подсказка 2')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='WriteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255, verbose_name='Вводимые данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_data_for_user', to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вводимые данные',
                'verbose_name_plural': 'Вводимые данные',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень №')),
                ('is_published_spoiler', models.BooleanField(default=False, verbose_name='Показать ли спойлер')),
                ('is_published_hint1', models.BooleanField(default=False, verbose_name='Показать ли подсказку 1')),
                ('is_published_hint2', models.BooleanField(default=False, verbose_name='Показать ли подсказку 2')),
                ('start_level_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Текущее время на уровне')),
                ('time_of_end_level', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время прохождения уровня')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_of_user', to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс команды',
                'verbose_name_plural': 'Прогресс команды',
            },
        ),
        migrations.CreateModel(
            name='FoundCodesForTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_codes', to='quest_app.codesonlevel', verbose_name='Найденный код')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_codes', to='quest_app.progress', verbose_name='Прогресс пользователя')),
            ],
            options={
                'verbose_name': 'Найденный код',
                'verbose_name_plural': 'Найденные коды',
            },
        ),
        migrations.AddField(
            model_name='codesonlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_for_level', to='quest_app.levels', verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ на загадку')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_for_level', to='quest_app.levels', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Ответ на загадку',
                'verbose_name_plural': 'Ответы на загадки',
            },
        ),
    ]
