# Generated by Django 4.0 on 2021-12-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='time_of_end_level',
        ),
        migrations.AlterField(
            model_name='levels',
            name='number_of_level',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='Уровень №'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время прохождения уровня')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='quest_app.levels', verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
