# Generated by Django 4.0 on 2021-12-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0002_remove_progress_time_of_end_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundcodesforteams',
            name='found_code',
            field=models.CharField(max_length=255, verbose_name='Найденный код'),
        ),
    ]
