# Generated by Django 4.0.2 on 2022-02-19 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0003_alter_foundcodesforteams_found_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='min_for_hint1',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Минут до 1 подсказки'),
        ),
        migrations.AddField(
            model_name='levels',
            name='min_for_hint2',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Минут до 2 подсказки'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_level_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время старта уровня'),
        ),
    ]
